const std = @import("std");
const cli = @import("cli.zig");
const compat = @import("compat.zig");

pub fn main(init: std.process.Init) !void {
    compat.setEnviron(init.minimal.environ);
    const allocator = init.arena.allocator();
    const args = try init.minimal.args.toSlice(allocator);
    const exit_code = cli.run(args, allocator) catch |err| {
        var buf: [128]u8 = undefined;
        const msg = std.fmt.bufPrint(&buf, "ztk: error: {s}\n", .{@errorName(err)}) catch "ztk: error\n";
        compat.writeStderr(msg) catch {};
        std.process.exit(1);
    };
    std.process.exit(exit_code);
}

test {
    _ = @import("cli.zig");
    _ = @import("stats.zig");
    _ = @import("stats_parse.zig");
    _ = @import("stats_render.zig");
    _ = @import("proxy.zig");
    _ = @import("proxy_session.zig");
    _ = @import("proxy_test.zig");
    _ = @import("executor.zig");
    _ = @import("simd/lines.zig");
    _ = @import("simd/ansi.zig");
    _ = @import("output.zig");
    _ = @import("filters/comptime.zig");
    _ = @import("filters/git_simple.zig");
    _ = @import("filters/git_status.zig");
    _ = @import("filters/git_status_v1.zig");
    _ = @import("filters/git_status_types.zig");
    _ = @import("filters/git_status_test.zig");
    _ = @import("filters/git_diff_condense.zig");
    _ = @import("filters/git_diff_test.zig");
    _ = @import("filters/git_log.zig");
    _ = @import("filters/git_log_body.zig");
    _ = @import("filters/git_log_test.zig");
    _ = @import("filters/test_cargo.zig");
    _ = @import("filters/test_nextest.zig");
    _ = @import("filters/test_pytest.zig");
    _ = @import("filters/test_go.zig");
    _ = @import("filters/test_node.zig");
    _ = @import("filters/files_ls.zig");
    _ = @import("filters/files_ls_parse.zig");
    _ = @import("filters/files_ls_ext.zig");
    _ = @import("filters/files_ls_format.zig");
    _ = @import("filters/files_ls_test.zig");
    _ = @import("filters/files_cat.zig");
    _ = @import("filters/files_cat_aggressive.zig");
    _ = @import("filters/files_grep.zig");
    _ = @import("filters/files_find.zig");
    _ = @import("filters/files_wc.zig");
    _ = @import("filters/files_headtail.zig");
    _ = @import("filters/files_python.zig");
    _ = @import("filters/filter_zig.zig");
    _ = @import("filters/docker.zig");
    _ = @import("filters/kubectl.zig");
    _ = @import("filters/filter_curl.zig");
    _ = @import("filters/filter_tree.zig");
    _ = @import("filters/filter_json.zig");
    _ = @import("filters/filter_gh.zig");
    _ = @import("filters/filter_log.zig");
    _ = @import("filters/filter_env.zig");
    _ = @import("filters/filter_build.zig");
    _ = @import("filters/filter_build_cargo.zig");
    _ = @import("filters/filter_build_tsc.zig");
    _ = @import("filters/filter_diag_block.zig");
    _ = @import("filters/filter_mypy.zig");
    _ = @import("filters/filter_go_build.zig");
    _ = @import("filters/filter_golangci.zig");
    _ = @import("filters/lint.zig");
    _ = @import("filters/lint_test.zig");
    _ = @import("session.zig");
    _ = @import("session_ops.zig");
    _ = @import("session_delta.zig");
    _ = @import("util/diff.zig");
    _ = @import("regex_compile.zig");
    _ = @import("regex_compile_test.zig");
    _ = @import("regex_compile_test2.zig");
    _ = @import("regex_types.zig");
    _ = @import("regex_parser.zig");
    _ = @import("regex_atom.zig");
    _ = @import("regex_quant.zig");
    _ = @import("regex_closure.zig");
    _ = @import("regex_simulate.zig");
    _ = @import("regex_match.zig");
    _ = @import("regex_replace.zig");
    _ = @import("regex_match_test.zig");
    _ = @import("filters/runtime.zig");
    _ = @import("filters/runtime_defs.zig");
    _ = @import("filters/runtime_apply.zig");
    _ = @import("filters/runtime_test.zig");
    _ = @import("hooks/permissions.zig");
    _ = @import("hooks/permissions_load.zig");
    _ = @import("hooks/permissions_match.zig");
    _ = @import("hooks/permissions_shell.zig");
    _ = @import("hooks/permissions_test.zig");
    _ = @import("hooks/claude.zig");
    _ = @import("hooks/claude_init.zig");
    _ = @import("hooks/claude_init_build.zig");
    _ = @import("hooks/claude_rewrite.zig");
    _ = @import("hooks/claude_test.zig");
}
